# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
name: Question
description: I want to ask a question
title: "os/gtime: issue title"
labels:
  - question

body:
  - type: textarea
    id: ask
    attributes:
      label: "What do you want to ask?"
      description: "Please read the document carefully. 请先仔细阅读文档"
    validations:
      required: true
